# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9NNHam7wdGfsplR_DUKAB2kbRDKudRG
"""

grade=input().split()
i=0
total=0
count=0
for a in grade:
  a=int(a)
  total+=int(a)
  count+=1
  if a<60:
    i=i+1
  else:
    continue
average=total/count
print(average)
print(i)