# -*- coding: utf-8 -*-
"""Score.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnB1Ot1yGMC7cSp9sXRy1bHVV8uJqQfk
"""

grade=input().split()
i=0
for a in grade:
  a=int(a)
  if a<60:
    i=i+1
  else:
    continue

print(i)