# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140ig7OvyR2nuDBF19Vo5u_M1V1DHby0m
"""

grade=input().split()
max_score=grade[0]
min_score=grade[0]
for a in grade:
  a=int(a)
  if a>int(max_score):
    max_score=a

  if a<int(min_score):
    min_score=a

print(max_score,min_score)